# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cameraSetting.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cameraSettingDialog(object):
    def setupUi(self, cameraSettingDialog):
        cameraSettingDialog.setObjectName("cameraSettingDialog")
        cameraSettingDialog.resize(380, 354)
        self.buttonBox = QtWidgets.QDialogButtonBox(cameraSettingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(cameraSettingDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 192, 280))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.coolerCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.coolerCheckBox.setText("")
        self.coolerCheckBox.setObjectName("coolerCheckBox")
        self.gridLayout.addWidget(self.coolerCheckBox, 5, 1, 1, 1)
        self.verticalSpeedSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.verticalSpeedSpinBox.setObjectName("verticalSpeedSpinBox")
        self.gridLayout.addWidget(self.verticalSpeedSpinBox, 8, 1, 1, 1)
        self.temperatureSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.temperatureSpinBox.setPrefix("")
        self.temperatureSpinBox.setObjectName("temperatureSpinBox")
        self.gridLayout.addWidget(self.temperatureSpinBox, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.frameNumberSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.frameNumberSpinBox.setMinimum(1)
        self.frameNumberSpinBox.setObjectName("frameNumberSpinBox")
        self.gridLayout.addWidget(self.frameNumberSpinBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.triggerComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.triggerComboBox.setObjectName("triggerComboBox")
        self.triggerComboBox.addItem("")
        self.triggerComboBox.addItem("")
        self.gridLayout.addWidget(self.triggerComboBox, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.frameTransferCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.frameTransferCheckBox.setText("")
        self.frameTransferCheckBox.setObjectName("frameTransferCheckBox")
        self.gridLayout.addWidget(self.frameTransferCheckBox, 1, 1, 1, 1)
        self.exposureTimeSpinBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.exposureTimeSpinBox.setDecimals(4)
        self.exposureTimeSpinBox.setMinimum(0.001)
        self.exposureTimeSpinBox.setMaximum(1000.0)
        self.exposureTimeSpinBox.setObjectName("exposureTimeSpinBox")
        self.gridLayout.addWidget(self.exposureTimeSpinBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.shutterComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.shutterComboBox.setObjectName("shutterComboBox")
        self.shutterComboBox.addItem("")
        self.shutterComboBox.addItem("")
        self.shutterComboBox.addItem("")
        self.gridLayout.addWidget(self.shutterComboBox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.verticalVoltageSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.verticalVoltageSpinBox.setMaximum(4)
        self.verticalVoltageSpinBox.setObjectName("verticalVoltageSpinBox")
        self.gridLayout.addWidget(self.verticalVoltageSpinBox, 7, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 0, 1, 1)
        self.horizontalVoltageSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.horizontalVoltageSpinBox.setObjectName("horizontalVoltageSpinBox")
        self.gridLayout.addWidget(self.horizontalVoltageSpinBox, 10, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 5, 0, 1, 1)
        self.verticalSpeedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.verticalSpeedLabel.setText("")
        self.verticalSpeedLabel.setObjectName("verticalSpeedLabel")
        self.gridLayout.addWidget(self.verticalSpeedLabel, 9, 1, 1, 1)
        self.horizontalSpeedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.horizontalSpeedLabel.setText("")
        self.horizontalSpeedLabel.setObjectName("horizontalSpeedLabel")
        self.gridLayout.addWidget(self.horizontalSpeedLabel, 11, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(cameraSettingDialog)
        self.groupBox.setGeometry(QtCore.QRect(210, 10, 141, 81))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 99, 48))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.hbinSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.hbinSpinBox.setMinimum(1)
        self.hbinSpinBox.setMaximum(512)
        self.hbinSpinBox.setObjectName("hbinSpinBox")
        self.gridLayout_2.addWidget(self.hbinSpinBox, 0, 1, 1, 1)
        self.vbinSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.vbinSpinBox.setMinimum(1)
        self.vbinSpinBox.setMaximum(512)
        self.vbinSpinBox.setObjectName("vbinSpinBox")
        self.gridLayout_2.addWidget(self.vbinSpinBox, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(cameraSettingDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 100, 161, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 146, 75))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.EMGainSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.EMGainSpinBox.setMaximum(300)
        self.EMGainSpinBox.setObjectName("EMGainSpinBox")
        self.gridLayout_3.addWidget(self.EMGainSpinBox, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.preAmplifySlider = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.preAmplifySlider.setMaximum(2)
        self.preAmplifySlider.setOrientation(QtCore.Qt.Horizontal)
        self.preAmplifySlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.preAmplifySlider.setObjectName("preAmplifySlider")
        self.gridLayout_3.addWidget(self.preAmplifySlider, 0, 1, 1, 1)
        self.EMGainCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.EMGainCheckBox.setText("")
        self.EMGainCheckBox.setObjectName("EMGainCheckBox")
        self.gridLayout_3.addWidget(self.EMGainCheckBox, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)

        self.retranslateUi(cameraSettingDialog)
        self.buttonBox.accepted.connect(cameraSettingDialog.accept)
        self.buttonBox.rejected.connect(cameraSettingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(cameraSettingDialog)

    def retranslateUi(self, cameraSettingDialog):
        _translate = QtCore.QCoreApplication.translate
        cameraSettingDialog.setWindowTitle(_translate("cameraSettingDialog", "Camera Setting"))
        self.label_12.setText(_translate("cameraSettingDialog", "Vertical Voltage"))
        self.temperatureSpinBox.setSuffix(_translate("cameraSettingDialog", "℃"))
        self.label_10.setText(_translate("cameraSettingDialog", "Temperature"))
        self.label_8.setText(_translate("cameraSettingDialog", "Frame Number"))
        self.triggerComboBox.setItemText(0, _translate("cameraSettingDialog", "Internal"))
        self.triggerComboBox.setItemText(1, _translate("cameraSettingDialog", "External"))
        self.label_7.setText(_translate("cameraSettingDialog", "Frame Transfer"))
        self.exposureTimeSpinBox.setSuffix(_translate("cameraSettingDialog", "ms"))
        self.label_2.setText(_translate("cameraSettingDialog", "Shutter"))
        self.label.setText(_translate("cameraSettingDialog", "Exposure Time"))
        self.shutterComboBox.setItemText(0, _translate("cameraSettingDialog", "Auto"))
        self.shutterComboBox.setItemText(1, _translate("cameraSettingDialog", "Open"))
        self.shutterComboBox.setItemText(2, _translate("cameraSettingDialog", "Close"))
        self.label_3.setText(_translate("cameraSettingDialog", "Trigger"))
        self.label_13.setText(_translate("cameraSettingDialog", "Vertical Speed"))
        self.label_14.setText(_translate("cameraSettingDialog", "Horizontal Speed"))
        self.label_15.setText(_translate("cameraSettingDialog", "Cooler"))
        self.groupBox.setTitle(_translate("cameraSettingDialog", "Binning"))
        self.label_6.setText(_translate("cameraSettingDialog", "Vertical"))
        self.label_5.setText(_translate("cameraSettingDialog", "Horizontal"))
        self.groupBox_2.setTitle(_translate("cameraSettingDialog", "Amplify"))
        self.label_9.setText(_translate("cameraSettingDialog", "EM Gain"))
        self.label_4.setText(_translate("cameraSettingDialog", "Pre Amplify"))
        self.label_11.setText(_translate("cameraSettingDialog", "EM Gain"))

